### ISSUE TITLE
why documentation suggests to use opentracing-cpp-v1.5.0 ?

### ISSUE THREAD

**Issue by chipitsine** [haproxytech/opentracing-c-wrapper#1]
```

  % wget https://github.com/opentracing/opentracing-cpp/archive/v1.5.0.tar.gz
  % tar xf v1.5.0.tar.gz
  % cd opentracing-cpp-1.5.0
  % mkdir build
  % cd build
  % cmake -DCMAKE_INSTALL_PREFIX=/opt ..
  % make
  # make install
```

there's 1.6.0 released.
any reason to stay on 1.5.0 ?

**Comment by zaga00** [comment]
Hello @chipitsine,

the reason is written in the README file:

"Of course, we can take another version of the library (or download the master
  branch via git).  For example, this version is used here due to compatibility
  with the Jaeger plugin, which I mostly used when testing the operation of the
  program."

In principle, version 1.5.1 might be appropriate, but with 1.6.0 there were some issues that made me to give it up.  I don't remember exactly what it was, probably because the Jaeger plugin for the newer version was not precompiled and compiling that version does not work on the debian I use (9).

Best regards.

**Comment by chipitsine** [comment]
oops
